services:
  postgres-tasks:
    image: postgres
    container_name: postgres_tasks
    networks:
      - app-network
    restart: always
    environment:
      POSTGRES_DB: 'task_tracker_tasks'
      POSTGRES_USER: 'tasktracker-user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5332:5432'
    volumes:
      - postgres_data_tasks:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak
    command:
      - start-dev
      - --https-certificate-file=/opt/keycloak/certs/localhost_rootca_.cer
      - --https-certificate-key-file=/opt/keycloak/certs/localhost_rootca_.p8.pem
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    restart: unless-stopped
    volumes:
      - ./ssl:/opt/keycloak/certs


networks:
  app-network:
    driver: bridge
  elk:
    driver: bridge


volumes:
  postgres_data_tasks:
