services:
  postgres-tasks:
    image: postgres
    container_name: postgres_tasks
    networks:
      - app-network
    restart: always
    environment:
      POSTGRES_DB: 'task_tracker_tasks'
      POSTGRES_USER: 'tasktracker-user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5332:5432'
    volumes:
      - postgres_data_tasks:/var/lib/postgresql/data

  postgres-users:
    image: postgres
    container_name: postgres_users
    networks:
      - app-network
    restart: always
    environment:
      POSTGRES_DB: 'task_tracker-users'
      POSTGRES_USER: 'tasktracker-user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5331:5432'
    volumes:
      - postgres_data_users:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin


networks:
  app-network:
    driver: bridge
  elk:
    driver: bridge


volumes:
  postgres_data_tasks:
  postgres_data_users: